export const surpriseMePrompts = [
  "A majestic castle on a floating island surrounded by clouds.",
  "A cozy cottage nestled in a field of blooming sunflowers.",
  "A futuristic cityscape with towering skyscrapers and flying ,cars.",
  "An enchanted forest filled with glowing mushrooms and mythical creatures.",
  "A serene beach at sunset with palm trees swaying in the breeze.",
  "A vibrant underwater world with coral reefs and exotic sea life.",
  "A bustling marketplace in an ancient Arabian city.",
  "A magical waterfall cascading into a hidden oasis.",
  "A tranquil lake surrounded by snow-capped mountains.",
  "A steampunk-inspired train station with steam-powered locomotives.",
  "A peaceful countryside scene with grazing sheep and rolling hills.",
  "A futuristic spaceport with rockets launching into the stars.",
  "A whimsical garden filled with talking animals and colorful flowers.",
  "A hauntingly beautiful abandoned mansion surrounded by mist.",
  "An alien landscape with bizarre rock formations and strange vegetation.",
  "A bustling Asian street market with lanterns and street food stalls.",
  "A cozy winter cabin with a crackling fireplace and snowy landscape.",
  "A medieval village with thatched-roof cottages and a village square.",
  "A surreal cityscape with upside-down buildings and floating objects.",
  "A secret garden hidden behind an ancient stone wall.",
  "A picturesque vineyard with rows of grapevines and a rustic winery.",
  "A mystical forest with towering trees and ethereal light.",
  "A grand ballroom filled with elegant dancers and a sparkling chandelier.",
  "A hidden cave with glowing crystals and a hidden treasure.",
  "A tranquil Zen garden with meticulously raked sand and bonsai trees.",
  "A floating island in the sky with waterfalls and lush vegetation.",
  "A futuristic laboratory with scientists conducting experiments.",
  "A bustling city intersection with cars and pedestrians in motion.",
  "A tropical paradise with white sandy beaches and crystal-clear waters.",
  "A charming European village with cobblestone streets and colorful houses.",
  "A majestic dragon soaring through the clouds.",
  "A serene mountain lake reflecting the surrounding peaks.",
  "A magical library filled with floating books and ancient manuscripts.",
  "A futuristic underwater city with glass domes and marine life.",
  "A bustling night market with vibrant lights and food stalls.",
  "A hidden waterfall in the heart of a lush rainforest.",
  "A floating city with buildings that resemble giant flowers.",
  "A whimsical carousel with brightly colored horses and music playing.",
  "An ancient Egyptian pyramid rising from the desert sands.",
  "A tranquil tea garden with cherry blossom trees and a koi pond.",
  "A futuristic cityscape at dusk with neon lights and holograms.",
  "A peaceful farm with grazing cows and a red barn in the distance.",
  "A magical castle perched on a cliff overlooking the sea.",
  "A bustling market square in a medieval European town.",
  "A picturesque lighthouse standing tall on a rocky coastline.",
  "A hidden pathway through a dense forest with sunlight peeking through.",
  "A futuristic city with flying cars and massive holographic billboards.",
  "A serene meadow with wildflowers swaying in the gentle breeze.",
  "A majestic waterfall surrounded by lush greenery and mist.",
  "A quaint cottage covered in ivy, nestled in a peaceful countryside.",
];
